name: Build & Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupération du code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Login à Docker Hub avec les secrets GitHub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 3) Build de l'image Docker avec npm install
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/mon-back:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/mon-back:${{ github.sha }} \
            ./back

      # 4) Push de l'image Docker (latest + SHA)
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mon-back:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mon-back:${{ github.sha }}
